#!groovy

// Generated by IBM TransformationAdvisor
// Tue Apr 30 01:40:30 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}